#!/bin/bash
echo "🐙 GitHub Repository Setup"
echo "========================="
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: submarine-faqs (or your preferred name)"
echo "3. Description: Comprehensive diesel-electric submarine FAQ collection"
echo "4. Make it Public (or Private if you prefer)"
echo "5. Don't initialize with README (we already have files)"
echo "6. Click 'Create repository'"
echo ""
echo "Then run these commands:"
echo ""
echo "git remote add origin https://github.com/YOURUSERNAME/submarine-faqs.git"
echo "git branch -M main"  
echo "git push -u origin main"
echo ""
echo "Replace YOURUSERNAME with your actual GitHub username"
