-- Seed data for glossary table
INSERT INTO glossary (term, definition) VALUES
('1MC', 'A general announcing system to all compartments in the submarine.'),
('7 MC', 'Announcing system to only some spaces.'),
('ADM', 'Admiral, comparable to a general. Generically, the five officer grades above a Navy captain.'),
('Aft', 'Toward the rear or after part of a ship or boat.'),
('Allied Powers In WW1', 'Initially, the main allied powers were Britain, France and Russia. The U.S., Italy and Japan joined later.'),
('Allied Powers In WW2', 'The main allied powers were the US, Britain (plus the Commonwealth countries, such as Canada, India, Australia and New Zealand) and Russia. France was an ally until it was defeated by Germany. Many other nations were actively allied with or leaning toward the allied side of the war.'),
('Amidships', 'The center of the boat, usually along the long (fore to aft) axis but can also be side to side.'),
('ASW', 'Anti-submarine warfare.'),
('Axis Powers In WW2', 'The main Axis Powers were Germany and Japan. Italy was an Axis nation until the overthrow of Mussolini in 1943. Even then, a large part of Italy was occupied by Germany. Other nations, particularly Spain and Argentina, were nominally neutral but in practice leaned toward the Axis.'),
('Ballast Tanks', 'Various tanks that could hold sea water used to dive and surface the boat. These tanks are along the side and below the pressure hull.'),
('Bathythermograph', 'A device that measures water temperatures at various depths as the submarine moves up and down in the water.'),
('Battle Station', 'An individual''s job when the submarine went into combat.'),
('Battle Stations', 'The condition when preparing to attack a target or being attacked. Also known as General Quarters.'),
('Bearing', 'Compass direction of an object or target.'),
('Berthing', 'Sleeping quarters.'),
('Bioluminescence', 'Plankton that glow when the water is disturbed, often by propellers. These plankton normally live in the deep but come near the surface at night to feed. When disturbed, they leave a streak in the water that glows for a few minutes.'),
('Bow Planes', 'A pair of wings or fins near the bow to control depth when submerged. The bow planes are "rigged in" when on the surface and are up against the superstructure to prevent damage from waves or swells. The plane on the star board side is visible from the pier. They are rigged out together in the process of diving. Bow planes are generally used for small changes in depth.'),
('Bubbleheads', 'Nickname for submariners.'),
('Bulkhead', 'Wall.'),
('CAPT', 'The Navy rank of captain or O-6, the sixth officer grade.'),
('Casualty', 'We think of a casualty most often in human terms. Casualties in war are the people that are injured or killed. However, we also speak of mechanical casualties. In this sense, it is equipment or machinery that breaks down or fails.'),
('CDR', 'The Navy rank of commander or O-5, the fifth officer grade.'),
('Central Powers', 'In WW1, this consisted of Germany, Austria-Hungary, the Ottoman Empire and Bulgaria.'),
('Charts', 'A map of part of the seas. It would include land masses in the area as well as the depth of the water, if known.'),
('Christmas Tree', 'The panel in the control room with multiple red and green lights. A red light indicates a critical valve or hatch is open; green shows that it is closed. A "green board" indicates that it is safe to dive. The panel is not shaped like a tree. The name comes from the colors used.'),
('CO', 'Commanding Officer, the position of captain of a ship.'),
('COB', 'Chief of the Boat. A specific position for the senior enlisted sailor on a boat. This chief petty officer is treated as the third most senior person on the boat, at the level of or above most officers. The COB is responsible for training, morale and informal discipline.'),
('Commissioned', 'For a submarine, it is when it is accepted by the Navy and put into service. Further testing with sea trials is still pending. For an officer, it is when he or she is sworn in and begins serving.'),
('Compartment', 'A room or space, part of the submarine.'),
('Chief Of The Watch', 'The senior enlisted watch who is stationed in the control room.'),
('Conn', 'Responsibility for control of the ship under the captain''s orders. The Officer of the Deck normally "has the conn."'),
('CPO', 'Chief petty officer, the highest enlisted grade.'),
('Cubicle', 'The electrical configuration in the maneuvering room where power from the generators and battery is directed and then distributed.'),
('Dead Reconning', 'Estimating your location based only on the direction, speed and time of your travel. This works well on land but, at sea, does not include the probable effects of wind and currents (set and drift). Navigators may have to add those impacts to have a more accurate estimate of the boat''s location.'),
('Depth Bomb', 'A bomb dropped from an aircraft to attack a submarine.'),
('Depth Charge', 'A device dropped or thrown from a surface ship to attack a submarine. It uses a pressure switch to explode at a predetermined depth. The ship using depth charges has to estimate the depth as well as the location of the submarine.'),
('Deck', 'Floor.'),
('Decommission', 'Taking a ship out of service. This could be temporary for major upgrades or for maintenance in the reserve fleet. It is more often permanent at the end of its useful life.'),
('Design Depth', 'The maximum depth for which the submarine was designed. For example, Balao class boats were designed for 600 feet. Fortunately, that is a conservative calculation. We know that boats such as the USS Pampanito have been below design depth and survived.'),
('Displacement', 'Essentially, the weight of a ship. The weight of the water that it displaces as it floats or submerges.'),
('Diving Officer', 'Officer or chief petty officer responsible for getting to and maintaining depth and neutral trim. Based on what the planes need to do to maintain depth, the diving officer then orders water pumped in and out of trim tanks, or between tanks, to get to neutral buoyancy.'),
('Dog The Watch', 'Dogging the watch is splitting one watch into two shifts. This has the effect of changing everyone''s watch forward by four hours so no one always stands watches at the same the times during the day and night.'),
('EB', 'Electric Boat, submarine building company located in New London and Groton, Connecticut.'),
('End Around', 'A maneuver to get back ahead of a target that was missed or turned away. The submarine would turn 90 degrees so it was perpendicular to the target. When it was far enough away from the target so it would not be seen, it would turn to the target''s course and run at high speed to get ahead of it. Ideally, the submarine can still see the masts or funnels of the target but the target wasn''t likely to see the boat''s periscope. When the boat is far enough ahead of the target, it would turn back toward the target''s expected position and prepare to attack.'),
('Enlisted', 'Crewmen who are not commissioned officers.'),
('ENS', 'The Navy rank of ensign; usually the first rank that an officer holds on graduating from the Naval Academy or college with a reserve officer training unit.'),
('Escape Trunk(s)', 'Trunks that can be used to escape from a sunken boat at depths down to around 200 feet.'),
('Fathom', 'A depth measurement of six feet. A traditional nautical measurement. Charts may specify depth in fathoms. Otherwise, the term is not often used by submarines.'),
('Fire Control', 'The process and equipment used to aim weapons at targets. This can be for guns or torpedoes, or even missiles.'),
('Fish', 'Slang for torpedoes. German U-boat sailors called their torpedoes "eels".'),
('Fix', 'Determining your location using stars or LORAN. These days it would be using stars or GPS.'),
('Flapper Valve', 'A flat valve that seals an opening. These valves are used where pressure against them helps seal them shut.'),
('Fleet Boats', 'Usually refers to the US subs built between WW1 and WW2. Some also consider the Gato/Balao/Tench classed as fleet boats. They were originally expected to operate with the fleet, but that wasn''t practical.'),
('Fore', 'Toward the front or forward part of the ship or boat.'),
('Foundered', 'Flooded with sea water and sank. Boats may founder due to operational errors or equipment failure. Sinking due to battle damage would normally be assigned to the damage as the primary cause rather than foundering.'),
('Fuel Ballast Tank', 'A ballast tank that was reconfigured to hold either water or fuel. Fuel in these tanks would be used first. Then the tank would be converted to a ballast tank and flushed.'),
('Fuel Tanks', 'Various tanks that hold diesel fuel for the engines. These tanks are among the ballast tanks located along the side and below the pressure hull.'),
('Galley', 'Space to prepare and cook meals.'),
('General Quarters', 'Battle stations.'),
('Goat Locker', 'Chief petty officers'' quarters.'),
('Gyrocompass', 'A ship''s compass that is based on the tendency of a gyroscope to remain oriented in space. In this case, the gyroscopes can remain oriented to north, and are not affected by the steel of the boat all around it.'),
('GUPPY', 'The Greater Underwater Propulsion Program conversion. This was a major upgrade for existing submarines begun after WW2. It included, among other things, removal of the guns and ready storage containers, addition of a snorkel, upgrading the batteries, and streamlining the sail. There were various levels of GUPPY upgrades. Some boats were only given a fleet snorkel upgrade which included much of the above but without the battery improvements.'),
('Hatch', 'Opening through a deck that allows movement up or down in a ship.'),
('Hedgehog', 'An anti-submarine weapon developed during WW2. Unlike a depth charge, it consisted of a circular pattern of smaller charges launched forward rather than a few large charges dropped from the stern. A hedgehog exploded when it made contact with a submarine rather than at a predetermined depth. These features meant that the attacking destroyer could use a slower attack speed and still have effective sonar. By the end of the war, hedgehogs achieved a kill once in every 5 or 6 launches. Depth charges were successful only once for every 80 charges dropped.'),
('IC Electrician', 'The rating responsible for interior communications equipment. This included alarms, motor order telegraphs, internal announcing system and sound-powered communication.'),
('IFF', 'Identification Friend or Foe. A radio frequency query used to determine whether a ship or aircraft is on our side.'),
('IJN', 'Imperial Japanese Navy.'),
('JANAC', 'Joint Army-Navy Assessment Committee to audit Japanese and American naval losses in WW2.'),
('Kingston Valve', 'Valves used both to vent ballast tanks and to flood water into the bottom of the tanks. Beginning with the early Gato boats, most of the flood valves were eliminated in favor of open ports at the bottom of the tanks. This allowed faster dives.'),
('Knot', 'A nautical mile or 2,027 yards. It is equal to 1.151 statute miles. It is defined as one minute of one degree of latitude at the equator. Sailors speak of speed at sea in knots (per hour). However, distances, which are in knots, are generally referred to as (nautical) miles, often rounded to 2,000 yards.'),
('Ladder', 'Stairs or steps on a ship.'),
('LCDR', 'The Navy rank of lieutenant commander or O-4, the grade above lieutenant. Many of our diesel submarine captains were lieutenant commanders when they assumed command.'),
('Leave', 'Extended time off, similar to vacation time in the civilian world.'),
('Liberty', 'Overnight or weekend time off for sailors when not on duty.'),
('Limber Holes', 'The holes along the side of the superstructure that look like windows. These openings allow water to quickly fill the space above the pressure hull and below the deck. They allow the submarine to dive and surface more quickly.'),
('LORAN', 'Long Range Aid to Navigation somewhat similar to GPS. The device uses ground-based radio stations rather than satellites.'),
('LT', 'The Navy rank of lieutenant or O-3, the third officer grade, above ensign and lieutenant junior grade. Some captains, most often the skippers of the older and smaller R and S class boats, were lieutenants.'),
('LTJG', 'Lieutenant, junior grade or O-2, the second officer grade, above ensign and below lieutenant.'),
('Mark', 'The designation of the "model" number of a device or weapon. For example, the Mark 14 torpedo was developed or designated just after the Mark 13 aerial torpedo (for aircraft) and before the Mark 15 version for surface ships.'),
('Main Induction', 'The large valve that allow air into the boat, primarily to run the engines.'),
('Maru', 'The Japanese word for a commercial or private ship. "Maru" is normally the last part of the ship''s name. "Maru" was not used for the names of Japanese warships.'),
('Mess', 'Space where the crew eats. Mess is a term used by all of the military, not just the Navy.'),
('MINSY', 'Mare Island Naval Shipyard, located in Vallejo in the San Francisco Bay Area.'),
('Mk', 'Short for "Mark".'),
('Neutral Buoyancy', 'Is the state of an object weighing as much as the water it displaces. The object floats but is submerged. If a submarine is in neutral buoyancy when submerged, it neither rises or settles. It tends to remain at the current depth. Note that neutral buoyancy may be changing frequently based on factors such as depth, water temperature and salinity.'),
('Motor Mac', 'The rating motor machinist mate. This would later evolve into engineman, which is a clearer description of the duties.'),
('Officer Of The Deck', 'Officer on duty who has control of the boat, under the direction of the captain. The OOD has the conn.'),
('Overhaul', 'A lengthy maintenance in a shipyard. This is for more extensive repairs than a refit. It often included significant repairs and equipment upgrades. Overhauls were usually done after six war patrols. Generally, it was also an opportunity for the crew to take some leave even though there was an intensive work schedule.'),
('Overhead', 'Ceiling.'),
('Passageway', 'An aisle or route through a ship.'),
('Periscopes', 'Complex tubes with mirrors and lenses that allow the user to see above the water.'),
('Periscope Shears', 'The structures housing and protecting the periscopes.'),
('Petty Officers', 'Enlisted ranks with increasing expertise and responsibility. Not commissioned officers.'),
('Pharmacist Mate', 'A Navy medic during WW2. Submarines did not have doctors assigned and, at this time, only our large missile boats do. Pharmacist mates are now known as hospital corpsmen.'),
('Picket', 'A ship or boat stationed between the fleet and the enemy to warn of approaching forces. Depending on the size and capability of the picket, it may also attempt to reduce the threat by attacking some of the hostile forces.'),
('PNSY', 'Portsmouth Naval Shipyard. It is named after Portsmouth, New Hampshire but is actually located in Kittery, Maine which is across the Piscataqua River.'),
('Port', 'The left side of the ship when facing forward. The word is used for clarity, rather than right or left.'),
('Position', 'Your location on the earth, usually on the open ocean.'),
('POW', 'Prisoner of war.'),
('PPI', 'The plan position indicator displays for radar and some sonar. This is the type of display that we think of with radar where a spot shows up on a display scope in the direction and at the distance of the item of interest. It was usually a ship or plane in WW2, but is now most often seen in weather reports.'),
('Pressure Hull', 'Inside part of the submarine where the men live and work. Sometimes known as the people pipe.'),
('PSI', 'Pounds per square inch, usually a measure of air or water pressure.'),
('Radar', 'Radio Detection And Ranging. An electronic method of using radio waves to locate objects around you. In this case, it would normally be enemy ships and aircraft, but it could also be features on land that can be used for navigation.'),
('Range', 'The distance to an object or target, usually given in yards.'),
('Reduction Gears', 'Large gears between the main motors and the propeller shafts. These gears allow the main motors to run efficiently while reducing the revolutions per minute that are transferred to the propeller shafts. Propeller shafts need to be able to run at much slower speeds than the main motors.'),
('Relative Bearing', 'Azimuth or direction to an object (target) relative to the direction that your ship is heading.'),
('Reverse Engineer', 'To create a copy by first studying and deconstructing an existing device.'),
('Reserve Fleet', 'Storage of ships that might be needed in the future. The ships are decommissioned, preserved and sealed so that, if needed, they can be restored to operation. Even if the ships need to be upgraded, the process is much faster than building new ships.'),
('Sail', 'The superstructure above the main deck enclosing the Conning Tower.'),
('Scuttle', 'The deliberate sinking of one''s own ship to prevent the enemy gaining access to fuel, weapons or classified information'),
('Sea Trials', 'Operating tests after commissioning or overhaul to identify any problems that still need to be corrected. The ship needs to be in commission so that the crew is assigned and able to conduct the tests.'),
('Sink', 'Process of sending a ship or boat to the bottom. A submarine that is descending beneath the surface is said to be diving or submerging. Hopefully, it is not sinking.'),
('Skivvies', 'Underwear, particularly undershorts.'),
('Smoking Lamp', 'General permission to smoke. Not literally a lamp any longer. Smoking was very common on WW2 boats and cigarettes were given away to servicemen during the war. Smoking is no longer allowed on submarines.'),
('Sonar', 'Sound Navigation And Ranging, an acronym similar in origin to radar. A method of using sound waves to locate objects around you. In this case, it would normally be enemy ships but could also be mines or the ocean bottom. Britain calls sonar ASDIC.'),
('Specific Gravity', 'The measurement of the electrolyte in the cells which indicates the amount of charge in the battery.'),
('SS', 'Steam ship, not a ship in the US Navy. Also, the designation that the hull number, as in "SS-383", is a submarine.'),
('Standing Watch', 'Working a shift while operating the submarine.'),
('Star Fix', 'Marking the elevation of known bright stars, usually three, along with the time noted. From that, the position (location) of the ship can be calculated.'),
('Starboard', 'The right side of the ship when facing forward. The word is used for clarity, rather than right or left.'),
('Stern Planes', 'A pair of short wings or fins near the stern to control depth when submerged. Unlike the bow planes, they are always rigged out. They are below water and protected by a guard. Stern planes are generally used for large changes in depth. They change the angle of the boat, up or down, so that forward motion changes the depth more quickly.'),
('Submerged', 'Operating while below the surface of the water.'),
('Superstructure', 'Part of the submarine above the pressure hull that includes the main deck.'),
('TBT', 'Target Bearing Transmitter.'),
('TDC', 'Torpedo Data Computer.'),
('Test Depth', 'The depth to which the boat is "tested". This is normally about two-thirds of design depth. For a Balao class boat like the USS Pampanito and designed for 600 feet, test depth would usually be between 400 and 450 feet. The boat is not intended to go below that depth for safety reasons. However, in wartime, you do what you have to do to survive and keep on fighting.'),
('Torpedo', 'A self-propelled underwater weapon used to damage and sink ships.'),
('Torpedo Skid Or Torpedo Rack', 'The tray on which reload torpedoes were stored until needed.'),
('Trim Dive', 'The first dive after leaving port or the daily dive while in transit. This would be a brief dive to get back to neutral buoyancy. The goal is to compensate for changes in the weight of the boat since it was last submerged.'),
('Trim Tanks', 'Internal tanks used to add or pump out water to get the boat to neutral buoyancy when submerged.'),
('True Bearings', 'Direction to another vessel or plane given in relationship to north, east, etc.'),
('Typhoon', 'A hurricane in the western Pacific is called a typhoon.'),
('Ultra', 'Highly classified messages based on code-breaking intelligence.'),
('USS (As In USS Pampanito)', 'United States Ship. A vessel of the US Navy.'),
('Watch', 'A normal shift when operating the submarine.'),
('Watertight Door', 'An opening between the compartments on the same level of a submarine.'),
('XO', 'Executive Officer. The position of second in command of a ship and administrative officer.');
